
package delivery.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Delivery", targetNamespace = "http://service.delivery/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Delivery {


    /**
     * 
     * @param parameters
     * @return
     *     returns delivery.service.AssignCourierResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "AssignCourierResp", targetNamespace = "http://service.delivery/", partName = "parameters")
    @Action(input = "get", output = "http://service.delivery/Delivery/assignCourierResponse")
    public AssignCourierResp assignCourier(
        @WebParam(name = "AssignCourierReq", targetNamespace = "http://service.delivery/", partName = "parameters")
        AssignCourierReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns delivery.service.CreateResp
     */
    @WebMethod(action = "create")
    @WebResult(name = "CreateResp", targetNamespace = "http://service.delivery/", partName = "parameters")
    @Action(input = "create", output = "http://service.delivery/Delivery/createDeliveryResponse")
    public CreateResp createDelivery(
        @WebParam(name = "CreateReq", targetNamespace = "http://service.delivery/", partName = "parameters")
        CreateReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns delivery.service.DeliveriesResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "DeliveriesResp", targetNamespace = "http://service.delivery/", partName = "parameters")
    @Action(input = "get", output = "http://service.delivery/Delivery/getClientDeliveriesResponse")
    public DeliveriesResp getClientDeliveries(
        @WebParam(name = "DeliveriesReq", targetNamespace = "http://service.delivery/", partName = "parameters")
        DeliveriesReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns delivery.service.CancelDeliveryResp
     */
    @WebMethod(action = "update")
    @WebResult(name = "CancelDeliveryResp", targetNamespace = "http://service.delivery/", partName = "parameters")
    @Action(input = "update", output = "http://service.delivery/Delivery/cancelDeliveryResponse")
    public CancelDeliveryResp cancelDelivery(
        @WebParam(name = "CancelDeliveryReq", targetNamespace = "http://service.delivery/", partName = "parameters")
        CancelDeliveryReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns delivery.service.UpdateDeliveryResp
     */
    @WebMethod(action = "update")
    @WebResult(name = "UpdateDeliveryResp", targetNamespace = "http://service.delivery/", partName = "parameters")
    @Action(input = "update", output = "http://service.delivery/Delivery/updateDeliveryResponse")
    public UpdateDeliveryResp updateDelivery(
        @WebParam(name = "UpdateDeliveryReq", targetNamespace = "http://service.delivery/", partName = "parameters")
        UpdateDeliveryReq parameters);

}
