
package delivery.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DeliveryService", targetNamespace = "http://service.delivery/", wsdlLocation = "http://localhost:9090/Delivery?wsdl")
public class DeliveryService
    extends Service
{

    private final static URL DELIVERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYSERVICE_EXCEPTION;
    private final static QName DELIVERYSERVICE_QNAME = new QName("http://service.delivery/", "DeliveryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/Delivery?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYSERVICE_WSDL_LOCATION = url;
        DELIVERYSERVICE_EXCEPTION = e;
    }

    public DeliveryService() {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME);
    }

    public DeliveryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME);
    }

    public DeliveryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Delivery
     */
    @WebEndpoint(name = "DeliveryPort")
    public Delivery getDeliveryPort() {
        return super.getPort(new QName("http://service.delivery/", "DeliveryPort"), Delivery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Delivery
     */
    @WebEndpoint(name = "DeliveryPort")
    public Delivery getDeliveryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.delivery/", "DeliveryPort"), Delivery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYSERVICE_EXCEPTION!= null) {
            throw DELIVERYSERVICE_EXCEPTION;
        }
        return DELIVERYSERVICE_WSDL_LOCATION;
    }

}
